version: '1.0'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    environment:
      - PORT=4000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - WS_URL=ws://localhost:4000
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
