version: '1.0'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - WS_URL=ws://localhost:8080
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
